name: SrLibras
description: Demonstrates how to use the flutter_blue plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^3.1.3
  path_provider: ^1.3.0
  path: 1.6.2
  flutter_file_manager: ^0.2.0
  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  firebase_ml_vision: ^0.9.2+1
  mlkit: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_blue:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
    - assets/a_2019-09-14 18_11_49.751063.txt